version: "3.8"

services:
  postgres:
    image: postgres:14.8
    hostname: postgres
    container_name: postgres
    networks:
      - promentor_net
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=admin
      - TIMESCALEDB_TELEMETRY=off
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./provision/postgres:/docker-entrypoint-initdb.d

  keycloak:
    depends_on:
      - postgres
    build:
      context: ./keycloak
    hostname: keycloak
    container_name: keycloak
    networks:
      - promentor_net
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB_URL=jdbc:postgresql://postgres/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak
      - KC_HOSTNAME=idp.promentor.local
      - KC_HTTP_ENABLED=true
      - KC_HOSTNAME_STRICT_HTTPS=false
      - DEBUG=true

networks:
  promentor_net:

volumes:
  db-data:
