version: "3.8"

services:
  postgres:
    image: postgres:14.8
    hostname: postgres
    container_name: postgres
    networks:
      - promentor_net
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=admin
      - TIMESCALEDB_TELEMETRY=off
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./provision/postgres:/docker-entrypoint-initdb.d

  keycloak:
    depends_on:
      - postgres
    build:
      context: ./keycloak
    hostname: keycloak
    container_name: keycloak
    networks:
      - promentor_net
    ports:
      - "${KEYCLOAK_EXTERNAL_PORT:-80}:8080"
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KC_DB_URL=${KC_DB_URL}
      - KC_DB_USERNAME=${KC_DB_USERNAME}
      - KC_DB_PASSWORD=${KC_DB_PASSWORD}
      - KC_HOSTNAME=${KC_HOSTNAME}
      - KC_HTTP_ENABLED=true
      - KC_HOSTNAME_STRICT_HTTPS=false
      - DEBUG=true
    volumes:
      - ./provision/keycloak:/tmp/import
    command:
      - "-Dkeycloak.migration.action=import"
      - "-Dkeycloak.migration.provider=dir"
      - "-Dkeycloak.migration.dir=/tmp/import"
      - "-Dkeycloak.migration.strategy=IGNORE_EXISTING"

networks:
  promentor_net:

volumes:
  db-data:
